name: Fetch Sidekiq Reliable Fetch Gem

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-gem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "mostafa@dahab.io"
          git config --global user.name "Mostafa Dahab"

      - name: Sparse checkout and update gem
        run: |
          git remote add upstream https://gitlab.com/gitlab-org/gitlab.git || true
          git config core.sparseCheckout true
          echo "vendor/gems/sidekiq-reliable-fetch" > .git/info/sparse-checkout
          git fetch --depth=1 upstream master
          git reset --hard upstream/master
          git clean -df

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Update sidekiq-reliable-fetch gem" || echo "No changes to commit"
          git push
