name: Fetch Sidekiq Reliable Fetch Gem

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  sync-gem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current GitHub repo
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Setup Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"

      - name: Sparse checkout from GitLab
        run: |
          git remote add gitlab https://gitlab.com/gitlab-org/gitlab.git || true
          git config core.sparseCheckout true
          echo "vendor/gems/sidekiq-reliable-fetch" > .git/info/sparse-checkout
          git fetch gitlab master --depth=1
          git checkout FETCH_HEAD
          git reset --soft HEAD@{1}

      - name: Commit and push changes to GitHub
        run: |
          git restore --staged .github  # Ensure .github directory is not included in the commit
          git commit -m "Update sidekiq-reliable-fetch gem from GitLab"
          git push origin main --force-with-lease
