name: Fetch Sidekiq Reliable Fetch Gem

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  sync-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to enable proper comparison and push

      - name: Setup Git
        run: |
          git config --global user.name 'Mostafa Dahab'
          git config --global user.email 'poweroftrue@users.noreply.github.com'

      - name: Sparse checkout from GitLab and prepare changes
        run: |
          # Your steps to fetch and prepare changes from GitLab go here

      - name: Exclude .github directory and commit changes
        run: |
          git restore --staged .github || echo ".github directory not changed"
          git commit -m "Update sidekiq-reliable-fetch gem from GitLab"
          git push origin main --force-with-lease
