name: Fetch Sidekiq Reliable Fetch Gem

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  sync-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to enable proper comparison and push

      - name: write dummy files
        run: |
          echo "dummy" > dummy.txt
          echo "dummy" > dummy2.txt
          echo "dummy" > dummy3.txt
          echo "dummy" > dummy4.txt
          echo "dummy" > dummy5.txt
          echo "dummy" > dummy6.txt
          echo "dummy" > dummy7.txt
          echo "dummy" > dummy8.txt
          echo "dummy" > dummy9.txt
          echo "dummy" > dummy10.txt
          echo "dummy" > dummy11.txt
          echo "dummy" > dummy12.txt
          echo "dummy" > dummy13.txt
          echo "dummy" > dummy14.txt
          echo "dummy" > dummy15.txt
          echo "dummy" > dummy16.txt
          echo "dummy" > dummy17.txt
          echo "dummy" > dummy18.txt
          echo "dummy" > dummy19.txt
          echo "dummy" > dummy20.txt
          echo "dummy" > dummy21.txt
          echo "dummy" > dummy22.txt
          echo "dummy" > dummy23.txt
          echo "dummy" > dummy24.txt
          echo "dummy" > dummy25.txt
          echo "dummy" > dummy26.txt
          echo "dummy" > dummy27.txt
          echo "dummy" > dummy28.txt
          echo "dummy" > dummy29.txt
          echo "dummy" > dummy30.txt
          echo "dummy" > dummy31.txt
          echo "dummy" > dummy32.txt
          echo "dummy" > dummy33.txt
          echo "dummy" > dummy34.txt
          echo "dummy" > dummy35.txt
          echo "dummy" > dummy36.txt
          echo "dummy" > dummy37.txt
          echo "dummy" > dummy38.txt
          echo "dummy" > dummy39.txt
          echo "dummy" > dummy40.txt
          echo "dummy" > dummy41.txt
          echo "dummy" > dummy42.txt
          echo "dummy" > dummy43.txt
          echo "dummy" > dummy44.txt
          echo "dummy" > dummy45.txt
          echo "dummy" > dummy46.txt
          echo "dummy" > dummy47.txt
          echo "dummy" > dummy48.txt
          echo "dummy" > dummy49.txt
          echo "dummy" > dummy50.txt

      - name: Exclude .github directory and commit changes
        run: |
          git restore --staged .github || echo ".github directory not changed"
          git config --global user.name 'Mostafa Dahab'
          git config --global user.email 'poweroftrue@users.noreply.github.com'
          git commit -am "Automated report"
          git push 
